# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UrlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('xpath', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=255)),
                ('site_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.UrlGroup')),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.UrlGroup'),
        ),
    ]
