# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
