# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20170515_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
