# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_remove_xfield_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='data',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
