# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_auto_20170517_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
