# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0007_xfield_rule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_enable', models.BooleanField(default=True)),
                ('placeholder', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='xfield',
            name='rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.RuleType'),
        ),
    ]
