# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0008_auto_20170517_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruletype',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
