# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0009_ruletype_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfield',
            name='rule',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
