# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0013_url_data_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
