# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0014_url_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruletype',
            name='default',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
