# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0015_ruletype_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruletype',
            name='default',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
