# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0017_auto_20170531_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
