# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 03:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0019_userplan_db_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlgroup',
            name='interval',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
