# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0020_urlgroup_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='data_sq',
            field=models.TextField(blank=True),
        ),
    ]
